name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake -B build/
      run: cmake
    - name: make
      run: make
      working-directory: build
    - name: make check
      run: make check
      working-directory: build
    - name: make distcheck
      run: make distcheck
      working-directory: build
